import subprocess
import os
import sys
from backup_mgr import create_full_backup, restore_from_backup


def run(cmd):
    try:
        subprocess.run(
            cmd,
            shell=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False)
    except Exception:
        pass


def apply_services():
    """Optimizaciones de servicios: Deshabilitar servicios innecesarios de Windows"""
    if os.name != "nt":
        sys.exit(1)

    # Create backup before applying services optimizations
    backup_info = create_full_backup("services")
    
    # Apply services optimizations
    run("sc config \\\"workfolderssvc\\\" start=disabled")
    run("sc config \\\"workfolderssvc\\\" start=demand")
    run("sc config \\\"workfolderssvc\\\" start= demand")
    run("sc config workfolderssvc start=disabled")
    run("sc stop workfolderssvc")
    run("sc config \\\"BTAGService\\\" start=manual")
    run("sc config BTAGService start= disabled")
    run("sc config BTAGService start=demand")
    run("sc config BTAGService start=disabled")
    run("sc config DPS start= Disabled")
    run("sc config \\\"UmRdpService\\\" start=disabled")
    run("sc config \\\"DPS\\\" start=disabled")
    run("sc config \\\"WdiServiceHost\\\" start=disabled")
    run("sc config \\\"WdiSystemHost\\\" start=disabled")
    run("sc config \\\"PcaSvc\\\" start=disabled")
    run("sc config \\\"diagsvc\\\" start=disabled")
    run("sc config \\\"SSDPSRV\\\" start=disabled")
    run("sc config PcaSvc start=disabled")
    run("sc config DPS start=disabled")
    run("sc config WdiServiceHost start=disabled")
    run("sc config WdiSystemHost start=disabled")
    run("sc config PcaSvc start= disabled")
    run("sc config SSDPSRV start= disabled")
    run("sc config diagsvc start= disabled")
    run("sc config UmRdpService start=disabled")
    run("sc config diagsvc start=disabled")
    run("sc config SSDPSRV start=disabled")
    run("sc config WdiServiceHost start= disabled")
    run("sc config WdiSystemHost start= disabled")
    run("sc config \\\"diagsvc\\\" start= disabled")
    run("sc config \\\"DPS\\\" start= disabled")
    run("sc config \\\"WdiServiceHost\\\" start= disabled")
    run("sc config \\\"WdiSystemHost\\\" start= disabled")
    run("sc config \\\"PcaSvc\\\" start= disabled")
    run("sc config \\\"SSDPSRV\\\" start=demand")
    run("sc config \\\"UmRdpService\\\" start=demand")
    run("sc config \\\"SSDPSRV\\\" start= demand")
    run("sc config \\\"UmRdpService\\\" start= demand")
    run("sc config \\\"WdiServiceHost\\\" start= demand")
    run("sc config \\\"WdiSystemHost\\\" start= demand")
    run("sc stop UmRdpService")
    run("sc stop DPS")
    run("sc stop WdiServiceHost")
    run("sc stop WdiSystemHost")
    run("sc stop PcaSvc")
    run("sc stop \\\"diagsvc\\\"")
    run("sc stop \\\"DPS\\\"")
    run("sc stop \\\"WdiServiceHost\\\"")
    run("sc stop \\\"WdiSystemHost\\\"")
    run("sc stop \\\"PcaSvc\\\"")
    run("sc stop diagsvc")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\AppModel\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Cellcore\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Circular Kernel Context Logger\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\CloudExperienceHostOobe\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\DataMarket\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\DiagLog\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\HolographicDevice\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\iclsClient\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\iclsProxy\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\LwtNetLog\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Mellanox-Kernel\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Microsoft-Windows-AssignedAccess-Trace\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Microsoft-Windows-Setup\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\NBSMBLOGGER\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\PEAuthLog\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\RdrLog\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\ReadyBoot\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\SetupPlatform\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\SetupPlatformTel\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\SocketHeciServer\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\SpoolerLogger\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\SQMLogger\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\TCPIPLOGGER\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\TileStore\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\Tpm\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\TPMProvisioningService\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\UBPM\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WdiContextLog\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WFP-IPsec Trace\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WiFiDriverIHVSession\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WiFiDriverIHVSessionRepro\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WiFiSession\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("Reg.exe add \\\"HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\WMI\\\\Autologger\\\\WinPhoneCritical\\\" /v \\\"Start\\\" /t REG_DWORD /d \\\"0\\\" /f")
    run("sc config \\\"CDPSvc\\\" start=disabled")
    run("sc config \\\"CDPUserSvc\\\" start=disabled")
    run("sc config \\\"InventorySvc\\\" start=demand")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskFootprint\\\\Diagnostics\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskFootprint\\\\Diagnostics\\\" /disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\DiskFootprint\\\\Diagnostics\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskFootprint\\\\Diagnostics\\\"")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Power Efficiency Diagnostics\\\\AnalyzeSystem\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Power Efficiency Diagnostics\\\\AnalyzeSystem\\\" /disable")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\MemoryDiagnostic\\\" /f")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Power Efficiency Diagnostics\\\\AnalyzeSystem\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Power Efficiency Diagnostics\\\\AnalyzeSystem\\\"")
    run("sc config \\\"WerSvc\\\" start=disabled")
    run("sc config \\\"wercplsupport\\\" start=demand")
    run("sc config WerSvc start=disabled")
    run("sc config wercplsupport start= disabled")
    run("sc config WerSvc start= disabled")
    run("sc config \\\"WerSvc\\\" start=demand")
    run("sc config \\\"wercplsupport\\\" start= demand")
    run("sc config \\\"WerSvc\\\" start= demand")
    run("sc config \\\"WerSvc\\\" start= disabled")
    run("sc config wercplsupport start=disabled")
    run("net stop WerSvc")
    run("sc stop WerSvc")
    run("sc stop \\\"WerSvc\\\"")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Windows Error Reporting\\\\QueueReporting\\\" /disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Windows Error Reporting\\\\QueueReporting\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Windows Error Reporting\\\\QueueReporting\\\"")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\Microsoft Compatibility Appraiser\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\ProgramDataUpdater\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\AitAgent\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\BthSQM\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\KernelCeipTask\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\UsbCeip\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticDataCollector\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticResolver\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyMonitor\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyRefresh\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyUpload\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Maintenance\\\\WinSAT\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\CloudExperienceHost\\\\CreateObjectTask\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\PI\\\\Sqm-Tasks\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\NetTrace\\\\GatherNetworkInfo\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\Automatic App Update\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Device Information\\\\Device\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\BthSQM\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\KernelCeipTask\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\UsbCeip\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\Microsoft Compatibility Appraiser\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\ProgramDataUpdater\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticDataCollector\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticResolver\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyMonitor\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyRefresh\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyUpload\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Maintenance\\\\WinSAT\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\AitAgent\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\CloudExperienceHost\\\\CreateObjectTask\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\PI\\\\Sqm-Tasks\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\NetTrace\\\\GatherNetworkInfo\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\Automatic App Update\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Device Information\\\\Device\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Device Information\\\\Device User\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\Scheduled Start\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Maps\\\\MapsUpdateTask\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\USO_UxBroker_Display\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\QueueReader\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\AITAgent\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\Schedule Scan\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\Scheduled Start\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\*\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\*\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Application Experience\\\\Microsoft Compatibility Appraiser\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\UsbCeip\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Maps\\\\MapsUpdateTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\NetTrace\\\\GatherNetworkInfo\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\NetTrace\\\\GatherNetworkInfo\\\"")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Application Experience\\\\ProgramDataUpdater\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Device Information\\\\Device\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Device Information\\\\Device User\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticDataCollector\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Maintenance\\\\WinSAT\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Maps\\\\MapsToastTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\PI\\\\Sqm-Tasks\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\Report policies\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\Schedule Scan\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\Schedule Scan Static Task\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\UpdateModelTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\USO_UxBroker\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\WindowsUpdate\\\\Scheduled Start\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\BthSQM\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\KernelCeipTask\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\UsbCeip\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\Microsoft Compatibility Appraiser\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\ProgramDataUpdater\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticDataCollector\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticResolver\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyMonitor\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyRefresh\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Shell\\\\FamilySafetyUpload\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Maintenance\\\\WinSAT\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\AitAgent\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\CloudExperienceHost\\\\CreateObjectTask\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\PI\\\\Sqm-Tasks\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Device Information\\\\Device\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Device Information\\\\Device User\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\WindowsUpdate\\\\Automatic App Update\\\"")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\KernelCeipTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\DiskDiagnostic\\\\Microsoft-Windows-DiskDiagnosticResolver\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\CloudExperienceHost\\\\CreateObjectTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Feedback\\\\WSCSecurityAudit\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateOrchestrator\\\\USO_UxBroker\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Maps\\\\MapsToastTask\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\MemoryDiagnostic\\\\ProcessMemoryDiagnosticEvents\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\MemoryDiagnostic\\\\RunFullMemoryDiagnostic\\\" /disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Windows Filtering Platform\\\\BfeOnServiceStartTypeChange\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Windows Filtering Platform\\\\BfeOnServiceStartTypeChange\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Input\\\\MouseSyncDataAvailable\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\StartupAppTask\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Consolidator\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Uploader\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Autochk\\\\Proxy\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\ForceSynchronizeTime\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\SynchronizeTime\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Consolidator\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Uploader\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\StartupAppTask\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Autochk\\\\Proxy\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\ForceSynchronizeTime\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\SynchronizeTime\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\HelloFace\\\\FODCleanupTask\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\PcaPatchDbTask\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Diagnosis\\\\Scheduled\\\" /DISABLE")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Performance\\\\PerfTrack\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\RAID Recovery\\\\Scheduled\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Servicing\\\\StartComponentCleanup\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Recovery Environment\\\\VerifyWinRE\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\BitLocker\\\\BitLocker Encrypt All Drives\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\BitLocker\\\\BitLocker MDM policy Refresh\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\ApplicationData\\\\DsSvcCleanup\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\TaskScheduler\\\\Maintenance Configurator\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\TaskScheduler\\\\Regular Maintenance\\\" /disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\TaskScheduler\\\\Idle Maintenance\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Speech\\\\SpeechModelDownloadTask\\\" /Disable")
    run("schtasks /change /tn \\\"\\\\Microsoft\\\\Windows\\\\Maintenance\\\\Regular Maintenance\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\UpdateAssistant\\\\*\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\WaaSMedic\\\\*\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Autochk\\\\Proxy\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Consolidator\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Application Experience\\\\MareBackup\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Application Experience\\\\StartupAppTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Application Experience\\\\PcaPatchDbTask\\\" /Disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Time Zone\\\\SynchronizeTimeZone\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\AppID\\\\EDP Policy Manager\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\AppID\\\\PolicyConverter\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\AppID\\\\VerifiedPublisherCertStoreCheck\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\ApplicationData\\\\appuriverifierdaily\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\ApplicationData\\\\appuriverifierinstall\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\BrokerInfrastructure\\\\BgTaskRegistrationMaintenanceTask\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\CertificateServicesClient\\\\AikCertEnrollTask\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\CertificateServicesClient\\\\KeyPreGenTask\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\Clip\\\\License Validation\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\DeviceDirectoryClient\\\\HandleCommand\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\DeviceDirectoryClient\\\\HandleWnsCommand\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\DeviceDirectoryClient\\\\IntegrityCheck\\\" /disable")
    run("schtasks /Change /TN \\\"\\\\Microsoft\\\\Windows\\\\DeviceDirectoryClient\\\\LocateCommandUserSession\\\" /disable")
    run("taskkill /f /im explorer.exe")
    run("taskkill /F /IM Teams.exe")
    run("taskkill /f /im msedge.exe")
    run("taskkill /f /im msedge.exe /fi \\\"IMAGENAME eq msedge.exe\\\"")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{E61FEADD-31CB-4052-8A16-1F4336764D10}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{E61FEADD-31CB-4052-8A16-1F4336764D10}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{E61FEADD-31CB-4052-8A16-1F4336764D10}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{880B9D61-BF97-4850-97D8-CD9EBFC4488A}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{880B9D61-BF97-4850-97D8-CD9EBFC4488A}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{880B9D61-BF97-4850-97D8-CD9EBFC4488A}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{7F2DA095-D54F-4B13-B246-9B6F33A50E83}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{CDF54DC6-6DCD-410E-A3F0-003BB1289F40}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{CDF54DC6-6DCD-410E-A3F0-003BB1289F40}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{7F2DA095-D54F-4B13-B246-9B6F33A50E83}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{CDF54DC6-6DCD-410E-A3F0-003BB1289F40}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{7F2DA095-D54F-4B13-B246-9B6F33A50E83}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Maps\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{2409B88C-473B-428B-8795-4C32D7822C9F}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{C9D09D2D-8C0A-4A0F-A699-4125AD19EF9C}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{74F6069B-3D81-479E-AA67-42CE80F16799}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{B97E9B4F-4348-4D52-8204-5EB3B9E3351C}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{74F6069B-3D81-479E-AA67-42CE80F16799}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{74F6069B-3D81-479E-AA67-42CE80F16799}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{B97E9B4F-4348-4D52-8204-5EB3B9E3351C}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{B97E9B4F-4348-4D52-8204-5EB3B9E3351C}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\RemoteApp and Desktop Connections Update\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\RemoteAssistance\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{10B3DD77-3048-41E7-A34D-5FF120D33FA4}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Logon\\\\{10B3DD77-3048-41E7-A34D-5FF120D33FA4}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Plain\\\\{10B3DD77-3048-41E7-A34D-5FF120D33FA4}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Device Setup\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\DeviceDirectoryClient\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Device Information\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Feedback\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\WDI\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Servicing\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{4C5BCB25-2C1D-40F3-A779-FDE6280DB867}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\Microsoft\\\\Windows\\\\Management\\\\Provisioning\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{0E511F8F-D1BF-49C8-B1B9-A6C784A17EDA}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{1D3D9B10-30A4-459E-8B32-248CAD0EB7EF}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{3EFB737D-965A-4364-8CBA-CCDA345B1C71}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{76300FA9-9EB5-4A2C-8087-029276F64728}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{825F76D6-EA34-4133-BF96-B416888766A3}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{8D567D13-E3B8-4273-84F4-C743E60872CC}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{BAE9F0C3-0DB3-494E-BC0B-42703170C272}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{C6D0FF06-5886-4924-93EB-851D6F3CBD06}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{81272F44-D745-4699-8216-955865606EAC}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{9FFC9FC7-ACE3-434F-A78C-43BBD0C1B871}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{8B551B42-E746-49C9-A6F3-D9B988AE0914}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{BE7B1C85-5B05-49EE-A887-1F23FF59A1EA}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{68AB1C40-FB5C-490E-9513-733CCED864C1}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{FB9EE28D-D0CA-4B6E-B47A-201C830C7006}\\\" /f")
    run("REG DELETE \\\"HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tasks\\\\{CD3A454B-E619-4AA6-85B5-B2D98ABC43A1}\\\" /f")
    run("taskkill /f /im CompatTelRunner.exe")
    run("taskkill /f /im maintenanceservice.exe")
    run("taskkill /f /im uninstall.exe")
    run("Reg.exe delete \\\"HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\MicrosoftEdgeUpdateTaskMachineCore\\\" /f")
    run("Reg.exe delete \\\"HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Schedule\\\\TaskCache\\\\Tree\\\\MicrosoftEdgeUpdateTaskMachineUA\\\" /f")
    run("schtasks /DELETE /TN \\\"AMDInstallLauncher\\\" /f")
    run("schtasks /DELETE /TN \\\"AMDLinkUpdate\\\" /f")
    run("schtasks /DELETE /TN \\\"AMDRyzenMasterSDKTask\\\" /f")
    run("schtasks /DELETE /TN \\\"Driver Easy Scheduled Scan\\\" /f")
    run("schtasks /DELETE /TN \\\"ModifyLinkUpdate\\\" /f")
    run("schtasks /DELETE /TN \\\"SoftMakerUpdater\\\" /f")
    run("schtasks /DELETE /TN \\\"StartCN\\\" /f")
    run("schtasks /DELETE /TN \\\"StartDVR\\\" /f")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Diagnosis\\\\RecommendedTroubleshootingScanner\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Diagnosis\\\\Scheduled\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\DUSM\\\\dusmtask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\EnterpriseMgmt\\\\MDMMaintenenceTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Flighting\\\\FeatureConfig\\\\ReconcileFeatures\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Flighting\\\\FeatureConfig\\\\UsageDataFlushing\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Flighting\\\\FeatureConfig\\\\UsageDataReporting\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Flighting\\\\OneSettings\\\\RefreshCache\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Input\\\\LocalUserSyncDataAvailable\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Input\\\\PenSyncDataAvailable\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Input\\\\TouchpadSyncDataAvailable\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\International\\\\Synchronize Language Settings\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\LanguageComponentsInstaller\\\\Installation\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\LanguageComponentsInstaller\\\\ReconcileLanguageResources\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\LanguageComponentsInstaller\\\\Uninstallation\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\License Manager\\\\TempSignedLicenseExchange\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Management\\\\Provisioning\\\\Cellular\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Management\\\\Provisioning\\\\Logon\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Mobile Broadband Accounts\\\\MNO Metadata Parser\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\MUI\\\\LPRemove\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\PushToInstall\\\\Registration\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Ras\\\\MobilityManager\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\RecoveryEnvironment\\\\VerifyWinRE\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\RemoteAssistance\\\\RemoteAssistanceTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\RetailDemo\\\\CleanupOfflineContent\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Servicing\\\\StartComponentCleanup\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Setup\\\\SetupCleanupTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Setup\\\\SnapshotCleanupTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\SpacePort\\\\SpaceAgentTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\SpacePort\\\\SpaceManagerTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Speech\\\\SpeechModelDownloadTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Task Manager\\\\Interactive\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Time Synchronization\\\\ForceSynchronizeTime\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Time Synchronization\\\\SynchronizeTime\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Time Zone\\\\SynchronizeTimeZone\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\TPM\\\\Tpm-HASCertRetr\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\TPM\\\\Tpm-Maintenance\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\UPnP\\\\UPnPHostConfig\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\User Profile Service\\\\HiveUploadTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\WDI\\\\ResolutionHost\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Work Folders\\\\Work Folders Logon Synchronization\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Work Folders\\\\Work Folders Maintenance Work\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Workplace Join\\\\Automatic-Device-Join\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\WwanSvc\\\\NotificationTask\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\WwanSvc\\\\OobeDiscovery\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\InstallService\\\\ScanForUpdates\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\InstallService\\\\ScanForUpdatesAsUser\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\InstallService\\\\SmartRetry\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\InstallService\\\\WakeUpAndContinueUpdates\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\InstallService\\\\WakeUpAndScanForUpdates\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\WaaSMedic\\\\PerformRemediation\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Printing\\\\EduPrintProv\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Printing\\\\PrinterCleanupTask\\\" /Disable")
    run("sc start \\\"BITS\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Consolidator\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Customer Experience Improvement Program\\\\Uploader\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\StartupAppTask\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Autochk\\\\Proxy\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Application Experience\\\\PcaPatchDbTask\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Office\\\\Office 15 Subscription Heartbeat\\\"")
    run("schtasks /change /TN \\\"\\\\Microsoft\\\\Office\\\\Office 15 Subscription Heartbeat\\\" /Disable")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\ForceSynchronizeTime\\\"")
    run("schtasks /end /tn \\\"\\\\Microsoft\\\\Windows\\\\Time Synchronization\\\\SynchronizeTime\\\"")
    run("schtasks /change /Disable /tn \\\"NvTmRep_CrashReport1_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /change /Disable /tn \\\"NvTmRep_CrashReport2_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /change /Disable /tn \\\"NvTmRep_CrashReport3_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /change /Disable /tn \\\"NvTmRep_CrashReport4_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /change /Disable /tn \\\"NvDriverUpdateCheckDaily_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /change /Disable /tn \\\"NvTmMon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}\\\"")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Location\\\\Notifications\\\" /Disable")
    run("schtasks /Change /TN \\\"Microsoft\\\\Windows\\\\Location\\\\WindowsActionDialog\\\" /Disable")


def get_backup_data():
    return {'backup_created': True}


def restore_from_backup_data(backup_data):
    if not backup_data:
        return
