import subprocess
import os
import sys


def run(cmd):
    try:
        subprocess.run(
            cmd,
            shell=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False)
    except Exception:
        pass


def apply_services_deep():
    if os.name != "nt":
        sys.exit(1)

    commands = [
        r'sc config DiagTrack start=disabled',
        r'sc stop DiagTrack',
        r'sc config dmwappushservice start=disabled',
        r'sc stop dmwappushservice',
        r'sc config MapsBroker start=disabled',
        r'sc stop MapsBroker',
        r'sc config lfsvc start=disabled',
        r'sc stop lfsvc',
        r'sc config SharedAccess start=disabled',
        r'sc stop SharedAccess',
        r'sc config TrkWks start=disabled',
        r'sc stop TrkWks',
        r'sc config WbioSrvc start=disabled',
        r'sc stop WbioSrvc',
        r'sc config XblAuthManager start=disabled',
        r'sc stop XblAuthManager',
        r'sc config XblGameSave start=disabled',
        r'sc stop XblGameSave',
        r'sc config XboxNetApiSvc start=disabled',
        r'sc stop XboxNetApiSvc',
        r'sc config XboxGipSvc start=disabled',
        r'sc stop XboxGipSvc',
        r'sc config RetailDemo start=disabled',
        r'sc stop RetailDemo',
        r'sc config RemoteRegistry start=disabled',
        r'sc stop RemoteRegistry',
        r'sc config Fax start=disabled',
        r'sc stop Fax',
        r'sc config fhsvc start=disabled',
        r'sc stop fhsvc',
        r'sc config irmon start=disabled',
        r'sc stop irmon',
        r'sc config SensrSvc start=disabled',
        r'sc stop SensrSvc',
        r'sc config WpcMonSvc start=disabled',
        r'sc stop WpcMonSvc',
        r'sc config PcaSvc start=disabled',
        r'sc stop PcaSvc',
        r'sc config DPS start=disabled',
        r'sc stop DPS',
        r'sc config WdiServiceHost start=disabled',
        r'sc stop WdiServiceHost',
        r'sc config WdiSystemHost start=disabled',
        r'sc stop WdiSystemHost',
        r'sc config SSDPSRV start=disabled',
        r'sc stop SSDPSRV',
        r'sc config upnphost start=disabled',
        r'sc stop upnphost',
        r'sc config diagsvc start=disabled',
        r'sc stop diagsvc',
        r'sc config diagnosticshub.standardcollector.service start=disabled',
        r'sc stop diagnosticshub.standardcollector.service',
        r'sc config WerSvc start=disabled',
        r'sc stop WerSvc',
        r'sc config wercplsupport start=disabled',
        r'sc stop wercplsupport',
        r'sc config OneSyncSvc start=disabled',
        r'sc stop OneSyncSvc',
        r'sc config MixedRealityOpenXRSvc start=disabled',
        r'sc stop MixedRealityOpenXRSvc',
        r'sc config MsKeyboardFilter start=disabled',
        r'sc stop MsKeyboardFilter',
        r'sc config icssvc start=disabled',
        r'sc stop icssvc',
        r'sc config PhoneSvc start=disabled',
        r'sc stop PhoneSvc',
        r'sc config TabletInputService start=disabled',
        r'sc stop TabletInputService',
        r'sc config WalletService start=disabled',
        r'sc stop WalletService',
        r'sc config wisvc start=disabled',
        r'sc stop wisvc',
        r'sc config wlidsvc start=demand',
        r'sc config WMPNetworkSvc start=disabled',
        r'sc stop WMPNetworkSvc',
        r'sc config HomeGroupProvider start=disabled',
        r'sc stop HomeGroupProvider',
        r'sc config HomeGroupListener start=disabled',
        r'sc stop HomeGroupListener',
        r'sc config SessionEnv start=disabled',
        r'sc stop SessionEnv',
        r'sc config UmRdpService start=disabled',
        r'sc stop UmRdpService',
        r'sc config TermService start=disabled',
        r'sc stop TermService',
        r'sc config RpcLocator start=disabled',
        r'sc stop RpcLocator',
        r'sc config stisvc start=disabled',
        r'sc stop stisvc',
        r'sc config SCardSvr start=disabled',
        r'sc stop SCardSvr',
        r'sc config SCPolicySvc start=disabled',
        r'sc stop SCPolicySvc',
        r'sc config NaturalAuthentication start=disabled',
        r'sc stop NaturalAuthentication',
        r'sc config WSearch start=disabled',
        r'sc stop WSearch',
        r'sc config BTAGService start=disabled',
        r'sc stop BTAGService',
        r'sc config bthserv start=disabled',
        r'sc stop bthserv',
        r'sc config tzautoupdate start=disabled',
        r'sc stop tzautoupdate',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\DiagTrack" /v Start /t REG_DWORD /d 4 /f',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\dmwappushservice" /v Start /t REG_DWORD /d 4 /f',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\WSearch" /v Start /t REG_DWORD /d 4 /f',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\WerSvc" /v Start /t REG_DWORD /d 4 /f',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\PcaSvc" /v Start /t REG_DWORD /d 4 /f',
        r'reg add "HKLM\SYSTEM\CurrentControlSet\Services\DPS" /v Start /t REG_DWORD /d 4 /f',
    ]

    for cmd in commands:
        run(cmd)


if __name__ == "__main__":
    apply_services_deep()
