import subprocess
import winreg
import ctypes
import sys

def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except:
        return False

if not is_admin():
    ctypes.windll.shell32.ShellExecuteW(None, "runas", sys.executable, " ".join(sys.argv), None, 1)
    sys.exit()

bcdedit_commands = [
    "bcdedit /set disabledynamictick yes",
    "bcdedit /deletevalue useplatformclock",
    "bcdedit /set useplatformtick yes",
    "bcdedit /set disabledynamictick yes",
    "bcdedit /set useplatformclock true",
    "bcdedit /set tscsyncpolicy Enhanced",
    "bcdedit /set useplatformtick yes",
    "bcdedit /set MSI default",
    "bcdedit /set usephysicaldestination no",
    "bcdedit /set usefirmwarepcisettings no",
    "bcdedit /set tscsyncpolicy legacy",
    "bcdedit /set x2apicpolicy enable",
    "bcdedit /set ems no",
    "bcdedit /set vm no",
    "bcdedit /set sos no",
    "bcdedit /set bootux disabled",
    "bcdedit /set bootlog no",
    "bcdedit /set tpmbootentropy ForceDisable",
    "bcdedit /set isolatedcontext no",
    "bcdedit /set pae ForceDisable",
    "bcdedit /set useplatformclock true",
    "bcdedit /set tscsyncpolicy Enhanced",
    "bcdedit /set disabledynamictick yes"
]

for cmd in bcdedit_commands:
    subprocess.run(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

registry_entries = [
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "ExitLatency", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "ExitLatencyCheckEnabled", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "HighPerformance", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "InitialUnparkCount", winreg.REG_DWORD, 100),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SD\IdleState\1", "IdleTimeLengthMs", winreg.REG_DWORD, 4294967295),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\1", "IdleTimeLengthMs", winreg.REG_DWORD, 4294967295),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerThrottling", "PowerThrottlingOff", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SD\IdleState\1", "IdleExitEnergyMicroJoules", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SD\IdleState\1", "IdleExitLatencyMs", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SD\IdleState\1", "IdlePowerMw", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\1", "IdleExitEnergyMicroJoules", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\1", "IdleExitLatencyMs", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\1", "IdlePowerMw", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\2", "IdleExitEnergyMicroJoules", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\2", "IdleExitLatencyMs", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\2", "IdlePowerMw", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\2", "IdleTimeLengthMs", winreg.REG_DWORD, 4294967295),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\3", "IdleExitEnergyMicroJoules", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\3", "IdleExitLatencyMs", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\3", "IdlePowerMw", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\Storage\SSD\IdleState\3", "IdleTimeLengthMs", winreg.REG_DWORD, 4294967295),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "GPU Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy", "DisableTaggedEnergyLogging", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy", "TelemetryMaxApplication", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy", "TelemetryMaxTagPerApplication", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "EnergyEstimationEnabled", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMin", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMax", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet001\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMax", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet001\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMin", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet002\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMax", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet002\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "ValueMin", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "MinimumThrottlePercent", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power", "MaximumThrottlePercent", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Session Manager\Throttle", "PerfEnablePackageIdle", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\ModernSleep", "CoalescingTimerInterval", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Attributes", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Affinity", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Background Only", winreg.REG_SZ, "False"),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Clock Rate", winreg.REG_DWORD, 10000),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Priority", winreg.REG_DWORD, 6),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Scheduling Category", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "BackgroundPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251_82be_4824_96c1_47b60b740d00\75b0ae3f_bce0_45a7_8c89_c9611c25e100", "Latency Sensitive", winreg.REG_SZ, "True"),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "Attributes", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\be337238-0d82-4146-a960-4f3749d470c7", "Attributes", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\0cc5b647-c1df-4637-891a-dec35c318583", "Attributes", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\893dee8e-2bef-41e0-89c6-b55d0929964c", "Attributes", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\bc5038f7-23e0-4960-96da-33abaf5935ec", "Attributes", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\ThrottleGPUInterference", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\PriorityControl", "Win32PrioritySeparation", winreg.REG_DWORD, 38),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\stornvme\Parameters\Device", "EnableHighPriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet001\Control\PriorityControl", "Win32PrioritySeparation", winreg.REG_DWORD, 38),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet001\Control\PriorityControl", "IRQ8Priority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ControlSet001\Control\PriorityControl", "IRQ16Priority", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"System\CurrentControlSet\Services\VxD\BIOS", "CPUPriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\BackgroundDefault", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Frozen", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNCS", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenDNK", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\FrozenPPLE", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Paused", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PausedDNK", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\Pausing", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Flags\PrelaunchForeground", "IsLowPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\PriorityControl", "IRQ8Priority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\PriorityControl", "IRQ16Priority", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Critical", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\CriticalNoUi", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\EmptyHostPPLE", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\High", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Low", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Lowest", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\Medium", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\MediumHigh", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\StartHost", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryHigh", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow", "BasePriority", winreg.REG_DWORD, 82),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\ResourcePolicyStore\ResourceSets\Policies\Importance\VeryLow", "OverTargetPriority", winreg.REG_DWORD, 50),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Session Manager\I/O System", "PassiveIntRealTimeWorkerPriority", winreg.REG_DWORD, 18),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\PriorityControl", "ConvertibleSlateMode", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeNonConforming", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeBestEffort", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeControlledLoad", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeGuaranteed", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeNetworkControl", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"Software\Policies\Microsoft\Windows\Psched\UserPriorityMapping", "ServiceTypeQualitative", winreg.REG_DWORD, 7),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\AFD\Parameters", "PriorityBoost", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel", "DisableAutoBoost", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\usbxhci\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\USBHUB3\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\NDIS\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\services\LanmanServer\Parameters", "ThreadPriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\DXGKrnl\Parameters", "ThreadPriority", winreg.REG_DWORD, 15),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\mouclass\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Services\kbdclass\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\services\amdkmdap\Parameters", "ThreadPriority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SYSTEM\CurrentControlSet\Control\Session Manager\kernel", "DpcTimeout", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\csrss.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "GPU Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "Priority", winreg.REG_DWORD, 6),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games", "Background Priority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Audio", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Playback", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Playback", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Capture", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Capture", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Distribution", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Distribution", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Pro Audio", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Pro Audio", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Window Manager", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Window Manager", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\DisplayPostProcessing", "GPU Priority", winreg.REG_DWORD, 31),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\DisplayPostProcessing", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\DisplayPostProcessing", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Network", "GPU Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Network", "Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Network", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Low Latency", "GPU Priority", winreg.REG_DWORD, 8),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Low Latency", "Priority", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Low Latency", "SFIO Priority", winreg.REG_SZ, "High"),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MsMpEng.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MsMpEngCP.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TiWorker.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TiWorker.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TiWorker.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MoUsoCoreWorker.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MoUsoCoreWorker.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\MoUsoCoreWorker.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Compattelrunner.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Compattelrunner.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Compattelrunner.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TrustedInstaller.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TrustedInstaller.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\TrustedInstaller.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenuExperienceHost.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenuExperienceHost.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenuExperienceHost.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenu.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenu.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\StartMenu.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\sppsvc.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 5),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\dwm.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntoskrnl.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 4),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntoskrnl.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wuauclt.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\wuauclt.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\audiodg.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\audiodg.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 2),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\lsass.exe\PerfOptions", "PagePriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntoskrnl.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 4),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ntoskrnl.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 3),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD, 1),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SearchIndexer.exe\PerfOptions", "IoPriority", winreg.REG_DWORD, 0),
    (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\svchost.exe\PerfOptions", "CpuPriorityClass", winreg.REG_DWORD